# Agent Queue 'Azure Pipelines' was used with unrecognized Agent Specification, vmImage property must be specified to determine image - https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#software
trigger:
  branches: 
    include:
    - __BRANCH_NAME__
name: $(date:yyyyMMdd)$(rev:.r)
jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    name: Azure Pipelines
  steps:
  - checkout: self
    fetchDepth: 1
  - task: Npm@1
    displayName: npm install
    inputs:
      workingDir: ./
      verbose: false
  - task: CopyFiles@2
    displayName: 'Copy Files to: ./'
    inputs:
      SourceFolder: ./
      Contents: >
        **\*.js

        **\*.json
      TargetFolder: ./
  - task: ArchiveFiles@2
    displayName: Archive files
    inputs:
      rootFolderOrFile: $(System.DefaultWorkingDirectory)
      includeRootFolder: false
  - task: PublishBuildArtifacts@1
    displayName: 'Publish artifacts: drop'
    inputs:
      TargetPath: '\\my\share\$(Build.DefinitionName)\$(Build.BuildNumber)'
...
